---
- name: capture remote servers os info
  hosts: all
  tasks:
    - name: capture os name
      debug:
        var: "{{ansible_distribution}}"
    - name: capture os version
      debug:
        var: "{{ansible_distribution_version}}"
    - name: capture os major version
      debug:
        var: "{{ansible_distribution_major_version}}"
