---
- name: create users on all servers
  hosts: all
  serial: 1
  tasks:
     - name: user creation
       user:
          name: shaik
          password: shaik123
          uid: 1111
          shell: /bin/bash
          comment: "A normal user"
          home: /tmp/shaik  

...
